# General Jekyll Config
name: UnProject
markdown: kramdown
highlighter: rouge
description: UnProject Archive
url: "https://bottled-ant.github.io/blog/"
lsi: false

exclude: [LICENCE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Build Settings
permalink: pretty
