# General Jekyll Config
name: UnProject
markdown: kramdown
highlighter: rouge
description: UnSeen Archive
url: "https://bottled-ant.github.io/UnSeen"
baseurl: /blog

exclude: [LICENCE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Build Settings
#permalink: pretty
